import { Random } from '$lib/utils/Random';

export class UsernameGenerator {

    private static usernames = [
        'Sophia Johnson',
        'Ethan Smith',
        'Olivia Davis',
        'Noah Williams',
        'Emma Brown',
        'Liam Miller',
        'Ava Anderson',
        'Jackson Taylor',
        'Isabella Martinez',
        'Aiden Thomas',
        'Mia Rodriguez',
        'Lucas Lopez',
        'Harper Lee',
        'Caden Gonzalez',
        'Charlotte Hernandez',
        'Elijah Wilson',
        'Amelia Clark',
        'Grayson Lewis',
        'Abigail Walker',
        'Jacob Green',
        'Emily Hall',
        'Michael Young',
        'Elizabeth Baker',
        'Benjamin Hill',
        'Sofia Adams',
        'Daniel Allen',
        'Avery Turner',
        'Matthew Nelson',
        'Scarlett Wright',
        'Joseph Carter',
        'Madison Mitchell',
        'Samuel Parker',
        'Grace Thompson',
        'David Carter',
        'Chloe Walker',
        'Henry Scott',
        'Victoria Roberts',
        'Josephine Moore',
        'Gabriel Garcia',
        'Lily Hill',
        'Andrew Phillips',
        'Penelope Morris',
        'Joshua Sanchez',
        'Brooklyn Turner',
        'Evelyn Bailey',
        'Christopher King',
        'Zoey Foster',
        'Wyatt Gray',
        'Natalie Wright',
        'Sebastian Ross',
        'Audrey Griffin',
        'Samuel Rivera',
        'Savannah Reed',
        'Isaac Powell',
        'Hannah Richardson',
        'Oliver Cox',
        'Stella Cook',
        'Matthew Brooks',
        'Leah Morgan',
        'Julian Ward',
        'Lillian Price',
        'Anthony Ramirez',
        'Lucy Cooper',
        'Leo Bell',
        'Samantha Kelly',
        'Christopher Bennett',
        'Eleanor James',
        'Lincoln Ward',
        'Layla Cox',
        'Nicholas Perry',
        'Maya Murphy',
        'Jack Turner',
        'Harper Watson',
        'Levi Mitchell',
        'Addison Simmons',
        'Andrew Coleman',
        'Hannah Edwards',
        'Joshua Collins',
        'Grace Parker',
        'Owen Morris',
        'Ellie Reed',
        'Caleb Roberts',
        'Violet Phillips',
        'Isaac Nelson',
        'Zoe Young',
        'Jeremiah Allen',
        'Skylar Davis',
        'Jonathan Morris',
        'Aurora Clark',
        'Eli Thomas',
        'Scarlett Adams',
        'Christian Rodriguez',
        'Paisley Gonzalez',
        'Josiah Reed',
        'Brooklyn Foster',
        'Evan Peterson',
        'Isla Diaz',
        'Jeremiah Cook',
        'Clara Bell',
        'Dominic Turner'
    ]

    public static generate() {
        const index = Random.numberBetween(0, UsernameGenerator.usernames.length - 1);
        return UsernameGenerator.usernames[index];
    }
}