databases:
  - name: svelte-chat-app-db
    plan: free
    region: frankfurt
    databaseName: chat
    user: frederik

services:
  - type: web
    plan: free
    region: frankfurt
    name: svelte-chat-app
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "node build/index.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: svelte-chat-app-db
          property: connectionString
      - key: NODE_VERSION 
        value: 20.2.0